# Generated by Django 6.0.5 on 2026-06-01 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
